### ISSUE TITLE
Can pangenie also work with GBS data? Genotyping-by-sequencing?

### ISSUE THREAD

**Issue by Yutang-ETH** [eblerjana/pangenie#25]
Hi pangenie team,

First of all, thank you very much for developing such a beautiful tool for the community.

I am wondering, instead of whole genome sequencing data, can pangenie also work with genotyping-by-sequencing (GBS) data? In plant breeding, people normally do GBS to save money since there might be hundreds of plants needed to be genotyped.

Looking forward to your answer and thank you very much in advance.

Best wishes,
Yutang

**Comment by eblerjana** [comment]
The model was designed mainly for whole genome sequencing data, since the k-mer-based information used for genotyping requires reads for the complete genome in order to properly estimate average k-mer coverages etc. Also, the variant information across the whole genome is important for PanGenie's to accurately impute genotypes in difficult regions. Therefore, I think that in its current form, it is not really suited for GBS data

**Comment by Yutang-ETH** [comment]
Thank you very much for your reply. Yes, I totally agree with you, it might be difficult to correctly impute genotypes between GBS sites. 

Best wishes,
Yutang
