### ISSUE TITLE
[question] Can variants vcf is single chromosome ? 

### ISSUE THREAD

**Issue by baozg** [eblerjana/pangenie#3]
Hi, @eblerjana 

Can the variants vcf is single chromosome ? For large-scale samples parallel, can we just use one chromosome vcf for genotyping/phasing? Or the pangenie must have whole genome variants for more precisely kmer counting and genotyping?

Thanks.
Zhigui Bao

**Comment by eblerjana** [comment]
If you run chromosomes individually, this might have an effect on the kmers used, because kmers might be identified as unique although they are not. I assume the differences are not too big, but I never really analyzed this in detail. However, I think it should be more efficient to run the whole genome at once, because the kmers need to be counted across the whole readset anyways, unless you have the read fastq split into chromosomes as well.

**Comment by baozg** [comment]
Thank you for the clarification.
