### ISSUE TITLE
How to represent structural variants in input VCF?

### ISSUE THREAD

**Issue by MehmetGoktay** [eblerjana/pangenie#9]
Hi,

Thank you very much for such a nice tool.

I would like to represent not only snps but also structural variants in the input VCF.

Could you please tell me how to do that?

This is my toy example:

##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##contig=<ID=1>
##ALT=<ID=DEL,Description="Deletion">
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00732	NA12878
1	15951	.	T	<DEL>	.	PASS	.	GT	0|0	1|1

-----------------------------------

End error message: 

VariantReader: skip variant at 1:15950 since alleles contain undefined nucleotides: <DEL>

Best,
Mehmet

**Comment by eblerjana** [comment]
The REF and ALT alleles must contain the full sequences of the variant. In your example, the ALT field is empty, but PanGenie needs sequence resolved calls since it needs them to determine allele-specific kmers. 
An insertion would for example look like this (this is just an invented example):

```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00732	NA12878
1	15951	.	T	TAGTGATCCTA	PASS	.	GT	0|0	1|1
```
One important thing that I mentioned also in the README is that PanGenie assumes the VCF to be a representation of a pangenome graph. Therefore, if reference coordinates of variants are overlapping, variants need to be merged prior to running PanGenie (otherwise it would filter them out). I provided a pipeline that does all this (see subfolder `pipelines/run-from-callset/`)

**Comment by MehmetGoktay** [comment]
Thank you very much for your quick response Jana!

I will do it that way then. You can close this issue. 

Best,
Mehmet
